from .curriculum_joint_variants import (
    ALL_ACTIVE_JOINT_NO_CURRICULUM,
    NEW_CONTEXT_200_THEN_JOINT_800,
)
from .joint_model_latent import SPEC as JOINT_MODEL_LATENT_TRAINING
from .per_trajectory_z import SPEC as PER_TRAJECTORY_Z
from .shuffled_grouping import SPEC as SHUFFLED_ENVIRONMENT_GROUPING

SPECS = (
    SHUFFLED_ENVIRONMENT_GROUPING,
    PER_TRAJECTORY_Z,
    JOINT_MODEL_LATENT_TRAINING,
    NEW_CONTEXT_200_THEN_JOINT_800,
    ALL_ACTIVE_JOINT_NO_CURRICULUM,
)

__all__ = [
    "ALL_ACTIVE_JOINT_NO_CURRICULUM",
    "JOINT_MODEL_LATENT_TRAINING",
    "NEW_CONTEXT_200_THEN_JOINT_800",
    "PER_TRAJECTORY_Z",
    "SHUFFLED_ENVIRONMENT_GROUPING",
    "SPECS",
]
